export default [
    {
      "gameId": 68448,
      "name": "7 Wonders",
      "image": "https://cf.geekdo-images.com/35h9Za_JvMMMtx_92kT0Jg__original/img/jt70jJDZ1y1FWJs4ZQf5FI8APVY=/0x0/filters:format(jpeg)/pic7149798.jpg",
      "thumbnail": "https://cf.geekdo-images.com/35h9Za_JvMMMtx_92kT0Jg__thumb/img/BUOso8b0M1aUOkU80FWlhE8uuxc=/fit-in/200x150/filters:strip_icc()/pic7149798.jpg",
      "minPlayers": 2,
      "maxPlayers": 7,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 2010,
      "bggRating": 0.0,
      "averageRating": 7.68625,
      "rank": 90,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 124742,
      "name": "Android: Netrunner",
      "image": "https://cf.geekdo-images.com/2ewHIIG_TRq8bYlqk0jIMw__original/img/cassW39WF2QrPImJF59efADAmM0=/0x0/filters:format(jpeg)/pic3738560.jpg",
      "thumbnail": "https://cf.geekdo-images.com/2ewHIIG_TRq8bYlqk0jIMw__thumb/img/IJaOyyQ7Y59tW6nbKbjTMTFt-Ls=/fit-in/200x150/filters:strip_icc()/pic3738560.jpg",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2012,
      "bggRating": 0.0,
      "averageRating": 7.87951,
      "rank": 72,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 139596,
      "name": "Android: Netrunner – Creation and Control",
      "image": "https://cf.geekdo-images.com/PU8uTHpNaawqeuk3HuAHlw__original/img/R6VXO1pemsvGXuBH0L_mgAGzkqg=/0x0/filters:format(jpeg)/pic1639594.jpg",
      "thumbnail": "https://cf.geekdo-images.com/PU8uTHpNaawqeuk3HuAHlw__thumb/img/rOxv9Q7Wid1VHsXu3HflSHrRKSY=/fit-in/200x150/filters:strip_icc()/pic1639594.jpg",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": 45,
      "isExpansion": true,
      "yearPublished": 2013,
      "bggRating": 0.0,
      "averageRating": 8.20683,
      "rank": -1,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 74,
      "name": "Apples to Apples",
      "image": "https://cf.geekdo-images.com/S5GzB_f2Re3kEDoSxqG5Ew__original/img/K49MN0Ij_tZOgDK4znCUJGu6aU4=/0x0/filters:format(jpeg)/pic213515.jpg",
      "thumbnail": "https://cf.geekdo-images.com/S5GzB_f2Re3kEDoSxqG5Ew__thumb/img/kJ1JQ_d9xEZ00sJ1dLvwyQYiQUA=/fit-in/200x150/filters:strip_icc()/pic213515.jpg",
      "minPlayers": 4,
      "maxPlayers": 10,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 1999,
      "bggRating": 0.0,
      "averageRating": 5.7552,
      "rank": 6869,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 27225,
      "name": "Bananagrams",
      "image": "https://cf.geekdo-images.com/1QjYPI4bXx4OUMJPlrsNBA__original/img/WA2NRNJx83xq81H2dnnwEDV2Ork=/0x0/filters:format(jpeg)/pic2463443.jpg",
      "thumbnail": "https://cf.geekdo-images.com/1QjYPI4bXx4OUMJPlrsNBA__thumb/img/nC_gG-4CYy7VBfYez2qSfTkU2ik=/fit-in/200x150/filters:strip_icc()/pic2463443.jpg",
      "minPlayers": 1,
      "maxPlayers": 8,
      "playingTime": 15,
      "isExpansion": false,
      "yearPublished": 2006,
      "bggRating": 0.0,
      "averageRating": 6.39114,
      "rank": 1982,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 10547,
      "name": "Betrayal at House on the Hill",
      "image": "https://cf.geekdo-images.com/lqmt2Oti_qJS65XqHcB8AA__original/img/7R6yYk8A2eUMmSDaxGjae5SceGI=/0x0/filters:format(png)/pic5146864.png",
      "thumbnail": "https://cf.geekdo-images.com/lqmt2Oti_qJS65XqHcB8AA__thumb/img/EDOmDbRhLy4za2PHkJ5IbhNxZmk=/fit-in/200x150/filters:strip_icc()/pic5146864.png",
      "minPlayers": 3,
      "maxPlayers": 6,
      "playingTime": 60,
      "isExpansion": false,
      "yearPublished": 2004,
      "bggRating": 0.0,
      "averageRating": 7.02896,
      "rank": 673,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 822,
      "name": "Carcassonne",
      "image": "https://cf.geekdo-images.com/okM0dq_bEXnbyQTOvHfwRA__original/img/aVZEXAI-cUtuunNfPhjeHlS4fwQ=/0x0/filters:format(png)/pic6544250.png",
      "thumbnail": "https://cf.geekdo-images.com/okM0dq_bEXnbyQTOvHfwRA__thumb/img/88274KiOg94wziybVHyW8AeOiXg=/fit-in/200x150/filters:strip_icc()/pic6544250.png",
      "minPlayers": 2,
      "maxPlayers": 5,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2000,
      "bggRating": 0.0,
      "averageRating": 7.4103,
      "rank": 215,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 13,
      "name": "CATAN",
      "image": "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/xV7oisd3RQ8R-k18cdWAYthHXsA=/0x0/filters:format(jpeg)/pic2419375.jpg",
      "thumbnail": "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__thumb/img/8a9HeqFydO7Uun_le9bXWPnidcA=/fit-in/200x150/filters:strip_icc()/pic2419375.jpg",
      "minPlayers": 3,
      "maxPlayers": 4,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 1995,
      "bggRating": 0.0,
      "averageRating": 7.0996,
      "rank": 546,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 171,
      "name": "Chess",
      "image": "https://cf.geekdo-images.com/0-DjGBOko6RV8zg5ejhYIg__original/img/0pn_QgMuWaIJb2Q7aZNfORse0_o=/0x0/filters:format(jpeg)/pic260745.jpg",
      "thumbnail": "https://cf.geekdo-images.com/0-DjGBOko6RV8zg5ejhYIg__thumb/img/kjtoinSrkYV0HZleXMxkJzZwS8k=/fit-in/200x150/filters:strip_icc()/pic260745.jpg",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": -1,
      "isExpansion": false,
      "yearPublished": 1475,
      "bggRating": 0.0,
      "averageRating": 7.20177,
      "rank": 446,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 178900,
      "name": "Codenames",
      "image": "https://cf.geekdo-images.com/F_KDEu0GjdClml8N7c8Imw__original/img/gcX_EfjsRpB5fI4Ug4XV73G4jGI=/0x0/filters:format(jpeg)/pic2582929.jpg",
      "thumbnail": "https://cf.geekdo-images.com/F_KDEu0GjdClml8N7c8Imw__thumb/img/yl8iXxSNwguMeg3KkmfFO9SMVVc=/fit-in/200x150/filters:strip_icc()/pic2582929.jpg",
      "minPlayers": 2,
      "maxPlayers": 8,
      "playingTime": 15,
      "isExpansion": false,
      "yearPublished": 2015,
      "bggRating": 0.0,
      "averageRating": 7.54592,
      "rank": 130,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 39463,
      "name": "Cosmic Encounter",
      "image": "https://cf.geekdo-images.com/S8cE-Ld7XP5sVz-upKJ-Bg__original/img/c4ZrfOtpp6tDHLyMsKecc2ne370=/0x0/filters:format(jpeg)/pic1521633.jpg",
      "thumbnail": "https://cf.geekdo-images.com/S8cE-Ld7XP5sVz-upKJ-Bg__thumb/img/gE--xqnuor4bft2J361zxJJGCjM=/fit-in/200x150/filters:strip_icc()/pic1521633.jpg",
      "minPlayers": 3,
      "maxPlayers": 5,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 2008,
      "bggRating": 0.0,
      "averageRating": 7.52496,
      "rank": 188,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 131357,
      "name": "Coup",
      "image": "https://cf.geekdo-images.com/MWhSY_GOe2-bmlQ2rntSVg__original/img/ayAAWBK1rAEumARNmROsOtvqW-4=/0x0/filters:format(jpeg)/pic2016054.jpg",
      "thumbnail": "https://cf.geekdo-images.com/MWhSY_GOe2-bmlQ2rntSVg__thumb/img/vuR_0PCX1w2EkjO_LbchOHZPOwU=/fit-in/200x150/filters:strip_icc()/pic2016054.jpg",
      "minPlayers": 2,
      "maxPlayers": 6,
      "playingTime": 15,
      "isExpansion": false,
      "yearPublished": 2012,
      "bggRating": 0.0,
      "averageRating": 6.98275,
      "rank": 634,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 156129,
      "name": "Deception: Murder in Hong Kong",
      "image": "https://cf.geekdo-images.com/1COY3oeK9aN2_XNimKaNww__original/img/ZzyzlO15ggCfkLg9ckeM4PWNePI=/0x0/filters:format(jpeg)/pic3033330.jpg",
      "thumbnail": "https://cf.geekdo-images.com/1COY3oeK9aN2_XNimKaNww__thumb/img/8IWDjnSYX-tYAVRgfq-W3y1b_Ww=/fit-in/200x150/filters:strip_icc()/pic3033330.jpg",
      "minPlayers": 4,
      "maxPlayers": 12,
      "playingTime": 20,
      "isExpansion": false,
      "yearPublished": 2014,
      "bggRating": 0.0,
      "averageRating": 7.4558,
      "rank": 239,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 36218,
      "name": "Dominion",
      "image": "https://cf.geekdo-images.com/j6iQpZ4XkemZP07HNCODBA__original/img/96COuakNiLRrjDLc1sM4Zxsw4WE=/0x0/filters:format(jpeg)/pic394356.jpg",
      "thumbnail": "https://cf.geekdo-images.com/j6iQpZ4XkemZP07HNCODBA__thumb/img/B2u2ghwlmI_qsUtCwuvcbnBcIqU=/fit-in/200x150/filters:strip_icc()/pic394356.jpg",
      "minPlayers": 2,
      "maxPlayers": 4,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 2008,
      "bggRating": 0.0,
      "averageRating": 7.59899,
      "rank": 118,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 172,
      "name": "For Sale",
      "image": "https://cf.geekdo-images.com/dJh9HkZC346NgPTAicJq_A__original/img/6ib2NLakSlsf69WYwCOe9NNLcsc=/0x0/filters:format(jpeg)/pic1513085.jpg",
      "thumbnail": "https://cf.geekdo-images.com/dJh9HkZC346NgPTAicJq_A__thumb/img/3cgW5aP-JJeKSpZMjA0NFheMnfY=/fit-in/200x150/filters:strip_icc()/pic1513085.jpg",
      "minPlayers": 3,
      "maxPlayers": 6,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 1997,
      "bggRating": 0.0,
      "averageRating": 7.25102,
      "rank": 331,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 194523,
      "name": "HMS Dolores",
      "image": "https://cf.geekdo-images.com/pzgKGIhvkNAZ3M3xaWWwow__original/img/H1mS58WBr_ziPpT-iZI6wxwwjH0=/0x0/filters:format(jpeg)/pic3105314.jpg",
      "thumbnail": "https://cf.geekdo-images.com/pzgKGIhvkNAZ3M3xaWWwow__thumb/img/LNpuYcJKdo8J8A9tJtK_SSOT854=/fit-in/200x150/filters:strip_icc()/pic3105314.jpg",
      "minPlayers": 2,
      "maxPlayers": 4,
      "playingTime": 20,
      "isExpansion": false,
      "yearPublished": 2016,
      "bggRating": 0.0,
      "averageRating": 6.11115,
      "rank": 4976,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 302520,
      "name": "Hues and Cues",
      "image": "https://cf.geekdo-images.com/jdR8WW75HkaoHGMTCIx9lA__original/img/i8nlw_c9CYgJMzixadYVh7GTTPc=/0x0/filters:format(jpeg)/pic5390676.jpg",
      "thumbnail": "https://cf.geekdo-images.com/jdR8WW75HkaoHGMTCIx9lA__thumb/img/EJ5gcczwsYvSavYuO4UoNPS45vo=/fit-in/200x150/filters:strip_icc()/pic5390676.jpg",
      "minPlayers": 3,
      "maxPlayers": 10,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 2020,
      "bggRating": 0.0,
      "averageRating": 6.60608,
      "rank": 2250,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 160499,
      "name": "King of New York",
      "image": "https://cf.geekdo-images.com/FGekxht_r5xqt8oSmQ9HZg__original/img/b5zgGvja0Qpte-Jqb5baQNWuG3c=/0x0/filters:format(jpeg)/pic2407103.jpg",
      "thumbnail": "https://cf.geekdo-images.com/FGekxht_r5xqt8oSmQ9HZg__thumb/img/DBoMebkqbcyZWJVLC5MRbF-YbnU=/fit-in/200x150/filters:strip_icc()/pic2407103.jpg",
      "minPlayers": 2,
      "maxPlayers": 6,
      "playingTime": 40,
      "isExpansion": false,
      "yearPublished": 2014,
      "bggRating": 0.0,
      "averageRating": 6.88676,
      "rank": 864,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 172503,
      "name": "Mage Wars Academy",
      "image": "https://cf.geekdo-images.com/BXqdHw39CPenDAKWDm_Vxw__original/img/pzO7kVTqFPx5mGYQXPxC39x4kL8=/0x0/filters:format(png)/pic2555236.png",
      "thumbnail": "https://cf.geekdo-images.com/BXqdHw39CPenDAKWDm_Vxw__thumb/img/RgBmCUFY-rCCHNC3uWAE3u8lTmA=/fit-in/200x150/filters:strip_icc()/pic2555236.png",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 2015,
      "bggRating": 0.0,
      "averageRating": 7.10176,
      "rank": 2392,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 181304,
      "name": "Mysterium",
      "image": "https://cf.geekdo-images.com/wfeAiLK5n5hD1omhnlYLLA__original/img/uhvKoYDfAsLg-nMkjQcbSJTDFmU=/0x0/filters:format(jpeg)/pic2601683.jpg",
      "thumbnail": "https://cf.geekdo-images.com/wfeAiLK5n5hD1omhnlYLLA__thumb/img/NAl-NrSAmWvklSVr3hKrSwiszNA=/fit-in/200x150/filters:strip_icc()/pic2601683.jpg",
      "minPlayers": 2,
      "maxPlayers": 7,
      "playingTime": 42,
      "isExpansion": false,
      "yearPublished": 2015,
      "bggRating": 0.0,
      "averageRating": 7.22342,
      "rank": 379,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 147949,
      "name": "One Night Ultimate Werewolf",
      "image": "https://cf.geekdo-images.com/KLDb0vR3w8mfaHgIGF0gHw__original/img/9YTYFSMwiRA01ZRNG0R5e9Rq01E=/0x0/filters:format(jpeg)/pic1809823.jpg",
      "thumbnail": "https://cf.geekdo-images.com/KLDb0vR3w8mfaHgIGF0gHw__thumb/img/ZgQsHsvdxXZr4DbMGUBSTArBp3o=/fit-in/200x150/filters:strip_icc()/pic1809823.jpg",
      "minPlayers": 3,
      "maxPlayers": 10,
      "playingTime": 10,
      "isExpansion": false,
      "yearPublished": 2014,
      "bggRating": 0.0,
      "averageRating": 7.06161,
      "rank": 590,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 2136,
      "name": "Pachisi",
      "image": "https://cf.geekdo-images.com/45Nb6goQqvPHD9hOut0ntg__original/img/PvDk6RoeXtEl1hsi1eIjeEKZqJk=/0x0/filters:format(jpeg)/pic516869.jpg",
      "thumbnail": "https://cf.geekdo-images.com/45Nb6goQqvPHD9hOut0ntg__thumb/img/ZtUXrh9wko9BQ3QLCMw9mU9Fjpw=/fit-in/200x150/filters:strip_icc()/pic516869.jpg",
      "minPlayers": 2,
      "maxPlayers": 6,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 400,
      "bggRating": 0.0,
      "averageRating": 4.51438,
      "rank": 25902,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 2651,
      "name": "Power Grid",
      "image": "https://cf.geekdo-images.com/yd6LuatytHRhcFCxCf-EEg__original/img/OS13C6W4i1XW__wWVVVaqF7BV0c=/0x0/filters:format(jpeg)/pic4459753.jpg",
      "thumbnail": "https://cf.geekdo-images.com/yd6LuatytHRhcFCxCf-EEg__thumb/img/jWTonZ5oYNlPzpELKHIJGWSS0Y8=/fit-in/200x150/filters:strip_icc()/pic4459753.jpg",
      "minPlayers": 2,
      "maxPlayers": 6,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 2004,
      "bggRating": 0.0,
      "averageRating": 7.8145,
      "rank": 60,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 3076,
      "name": "Puerto Rico",
      "image": "https://cf.geekdo-images.com/QFiIRd2kimaMqTyWsX0aUg__original/img/DOgIp57F7tKZvxeITGAd3e_Q9as=/0x0/filters:format(jpeg)/pic158548.jpg",
      "thumbnail": "https://cf.geekdo-images.com/QFiIRd2kimaMqTyWsX0aUg__thumb/img/5fLo89ChZH6Wzukk36bhZ-EpBS0=/fit-in/200x150/filters:strip_icc()/pic158548.jpg",
      "minPlayers": 3,
      "maxPlayers": 5,
      "playingTime": 150,
      "isExpansion": false,
      "yearPublished": 2002,
      "bggRating": 0.0,
      "averageRating": 7.92099,
      "rank": 43,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 329082,
      "name": "Radlands",
      "image": "https://cf.geekdo-images.com/YpQUtpxNtDHBF5eVcwzBtQ__original/img/br-kw0KuyBfH1mrxZ0kgVrF9UMc=/0x0/filters:format(png)/pic6478338.png",
      "thumbnail": "https://cf.geekdo-images.com/YpQUtpxNtDHBF5eVcwzBtQ__thumb/img/tN06HL-O6O-ayKHxEio9xYoJym0=/fit-in/200x150/filters:strip_icc()/pic6478338.png",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": 40,
      "isExpansion": false,
      "yearPublished": 2021,
      "bggRating": 0.0,
      "averageRating": 7.87671,
      "rank": 175,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 41114,
      "name": "The Resistance",
      "image": "https://cf.geekdo-images.com/cAPTkL2BR3snLO71dkH8rw__original/img/_UahoIUTqh39xRqzCc2jwgdYbSA=/0x0/filters:format(jpeg)/pic2576459.jpg",
      "thumbnail": "https://cf.geekdo-images.com/cAPTkL2BR3snLO71dkH8rw__thumb/img/5lDn1W82rlLXtVG7nPIYR9Orn-4=/fit-in/200x150/filters:strip_icc()/pic2576459.jpg",
      "minPlayers": 5,
      "maxPlayers": 10,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 2009,
      "bggRating": 0.0,
      "averageRating": 7.21798,
      "rank": 387,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 181,
      "name": "Risk",
      "image": "https://cf.geekdo-images.com/Oem1TTtSgxOghRFCoyWRPw__original/img/Nu3eXPyOkhtnR3hhpUrtgqRMAfs=/0x0/filters:format(jpeg)/pic4916782.jpg",
      "thumbnail": "https://cf.geekdo-images.com/Oem1TTtSgxOghRFCoyWRPw__thumb/img/5cltSV60oVvjL3Ag_KTJbmTdU6w=/fit-in/200x150/filters:strip_icc()/pic4916782.jpg",
      "minPlayers": 2,
      "maxPlayers": 6,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 1959,
      "bggRating": 0.0,
      "averageRating": 5.59367,
      "rank": 25169,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 216201,
      "name": "Robo Rally",
      "image": "https://cf.geekdo-images.com/ZiAz-uo9YfbOIx_FAjgvvQ__original/img/dWtc6I9fsndFbZVKMBRSKNNazow=/0x0/filters:format(jpeg)/pic3374227.jpg",
      "thumbnail": "https://cf.geekdo-images.com/ZiAz-uo9YfbOIx_FAjgvvQ__thumb/img/YgYrT9-ym_g8T2WP7uBOamEO9ig=/fit-in/200x150/filters:strip_icc()/pic3374227.jpg",
      "minPlayers": 2,
      "maxPlayers": 6,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 2016,
      "bggRating": 0.0,
      "averageRating": 6.97256,
      "rank": 1524,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 132531,
      "name": "Roll for the Galaxy",
      "image": "https://cf.geekdo-images.com/nhoyoLpYPC2b3UiJ5kJ0yg__original/img/LoETJCbq1HpSlhPLdci3qJekpwA=/0x0/filters:format(jpeg)/pic1473629.jpg",
      "thumbnail": "https://cf.geekdo-images.com/nhoyoLpYPC2b3UiJ5kJ0yg__thumb/img/KVmexHT6N_fquB1CQl9QRNYCvD0=/fit-in/200x150/filters:strip_icc()/pic1473629.jpg",
      "minPlayers": 2,
      "maxPlayers": 5,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2014,
      "bggRating": 0.0,
      "averageRating": 7.59425,
      "rank": 137,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 169426,
      "name": "Roll Player",
      "image": "https://cf.geekdo-images.com/enmQAOQl99U6wiQvZoL5GQ__original/img/iiKhufERu8v8JpErc5kUoO8WiNw=/0x0/filters:format(jpeg)/pic2556921.jpg",
      "thumbnail": "https://cf.geekdo-images.com/enmQAOQl99U6wiQvZoL5GQ__thumb/img/zdtrILXRjphkt5HYP0tuxzlenG4=/fit-in/200x150/filters:strip_icc()/pic2556921.jpg",
      "minPlayers": 1,
      "maxPlayers": 4,
      "playingTime": 90,
      "isExpansion": false,
      "yearPublished": 2016,
      "bggRating": 0.0,
      "averageRating": 7.45402,
      "rank": 249,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 199561,
      "name": "Sagrada",
      "image": "https://cf.geekdo-images.com/PZt3EAAGV3dFIVuwMR0AEw__original/img/5ug9EeKlH_ucJEUXaFpTZbBJ1GY=/0x0/filters:format(jpeg)/pic3525224.jpg",
      "thumbnail": "https://cf.geekdo-images.com/PZt3EAAGV3dFIVuwMR0AEw__thumb/img/1m4aryOW1MOpq-8jGkF6gDTJmCY=/fit-in/200x150/filters:strip_icc()/pic3525224.jpg",
      "minPlayers": 1,
      "maxPlayers": 4,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2017,
      "bggRating": 0.0,
      "averageRating": 7.47861,
      "rank": 193,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 194655,
      "name": "Santorini",
      "image": "https://cf.geekdo-images.com/665Ply7Ho1WVf1v1iZlWeg__original/img/4q6RCxd7st-yW2MyrJwVC_d3ajk=/0x0/filters:format(png)/pic3283110.png",
      "thumbnail": "https://cf.geekdo-images.com/665Ply7Ho1WVf1v1iZlWeg__thumb/img/BKnSb6kAhpVFHV8cyUXrs3EF_dw=/fit-in/200x150/filters:strip_icc()/pic3283110.png",
      "minPlayers": 2,
      "maxPlayers": 4,
      "playingTime": 20,
      "isExpansion": false,
      "yearPublished": 2016,
      "bggRating": 0.0,
      "averageRating": 7.3673,
      "rank": 259,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 232595,
      "name": "Skulk Hollow",
      "image": "https://cf.geekdo-images.com/wycq-tJqtKsUkYADq8Z3BQ__original/img/6K49PugCJeHYWOuapYfKBN92e5w=/0x0/filters:format(jpeg)/pic7083310.jpg",
      "thumbnail": "https://cf.geekdo-images.com/wycq-tJqtKsUkYADq8Z3BQ__thumb/img/UFcTi7i4rbCy1a05mztemxSDL5I=/fit-in/200x150/filters:strip_icc()/pic7083310.jpg",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": 40,
      "isExpansion": false,
      "yearPublished": 2019,
      "bggRating": 0.0,
      "averageRating": 7.25427,
      "rank": 1547,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 92415,
      "name": "Skull",
      "image": "https://cf.geekdo-images.com/OPrd2iXm43dir7BwKAMOuQ__original/img/ygPnbmg8FCpA7jO5gXw38uyNQ10=/0x0/filters:format(jpeg)/pic6097488.jpg",
      "thumbnail": "https://cf.geekdo-images.com/OPrd2iXm43dir7BwKAMOuQ__thumb/img/yEnb4YWN-Cp41KWTQ2EeNkrqlZI=/fit-in/200x150/filters:strip_icc()/pic6097488.jpg",
      "minPlayers": 3,
      "maxPlayers": 6,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2011,
      "bggRating": 0.0,
      "averageRating": 7.19287,
      "rank": 430,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 40692,
      "name": "Small World",
      "image": "https://cf.geekdo-images.com/aoPM07XzoceB-RydLh08zA__original/img/bYLzrwZO9u-3h2wyU-PHc8aTOY4=/0x0/filters:format(jpeg)/pic428828.jpg",
      "thumbnail": "https://cf.geekdo-images.com/aoPM07XzoceB-RydLh08zA__thumb/img/o3Bw9heVDJRgPYlI_PksCvLAgnM=/fit-in/200x150/filters:strip_icc()/pic428828.jpg",
      "minPlayers": 2,
      "maxPlayers": 5,
      "playingTime": 80,
      "isExpansion": false,
      "yearPublished": 2009,
      "bggRating": 0.0,
      "averageRating": 7.21007,
      "rank": 352,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 38453,
      "name": "Space Alert",
      "image": "https://cf.geekdo-images.com/tinE1f2lauIsEL4aC9aU-w__original/img/ccy5tGJK7WF9B6ykayJEm5cReTM=/0x0/filters:format(jpeg)/pic384313.jpg",
      "thumbnail": "https://cf.geekdo-images.com/tinE1f2lauIsEL4aC9aU-w__thumb/img/9tewdwxUKcqikj0QlVSUmwRPK68=/fit-in/200x150/filters:strip_icc()/pic384313.jpg",
      "minPlayers": 1,
      "maxPlayers": 5,
      "playingTime": 30,
      "isExpansion": false,
      "yearPublished": 2008,
      "bggRating": 0.0,
      "averageRating": 7.39633,
      "rank": 313,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 103885,
      "name": "Star Wars: X-Wing Miniatures Game",
      "image": "https://cf.geekdo-images.com/yNqgVxaqoZepir7Hzkfe-Q__original/img/H6rYWOhYjT_PXTrvHKyX6FEt-vw=/0x0/filters:format(jpeg)/pic1603292.jpg",
      "thumbnail": "https://cf.geekdo-images.com/yNqgVxaqoZepir7Hzkfe-Q__thumb/img/idalbLcUm2q9yxVZzRDkLEax5AE=/fit-in/200x150/filters:strip_icc()/pic1603292.jpg",
      "minPlayers": 2,
      "maxPlayers": 2,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2012,
      "bggRating": 0.0,
      "averageRating": 7.63811,
      "rank": 165,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 2653,
      "name": "Survive: Escape from Atlantis!",
      "image": "https://cf.geekdo-images.com/0M2ck50-GanxBWfOHUZ64A__original/img/5VKS6zuDQlHBQcTcDNRNFYu-7Bg=/0x0/filters:format(png)/pic1300182.png",
      "thumbnail": "https://cf.geekdo-images.com/0M2ck50-GanxBWfOHUZ64A__thumb/img/6ffKBS6bTCKgCmH7zdHJIxcU8ZA=/fit-in/200x150/filters:strip_icc()/pic1300182.png",
      "minPlayers": 2,
      "maxPlayers": 4,
      "playingTime": 60,
      "isExpansion": false,
      "yearPublished": 1982,
      "bggRating": 0.0,
      "averageRating": 7.31461,
      "rank": 328,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 192291,
      "name": "Sushi Go Party!",
      "image": "https://cf.geekdo-images.com/2f9uTicUSXkdPp2Yks6zFw__original/img/WQcFmlhYBMIp8f6gNNVhnnue1w4=/0x0/filters:format(jpeg)/pic5885689.jpg",
      "thumbnail": "https://cf.geekdo-images.com/2f9uTicUSXkdPp2Yks6zFw__thumb/img/_mXR9Tlo0f-i80h6pfhDEOBgvpY=/fit-in/200x150/filters:strip_icc()/pic5885689.jpg",
      "minPlayers": 2,
      "maxPlayers": 8,
      "playingTime": 20,
      "isExpansion": false,
      "yearPublished": 2016,
      "bggRating": 0.0,
      "averageRating": 7.39955,
      "rank": 250,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 5336,
      "name": "Talisman (Third Edition)",
      "image": "https://cf.geekdo-images.com/c_GmyHR6gi9ZCkIQaSL0ZA__original/img/DzMdXHxiGaNqGckFhMVddUR1aMg=/0x0/filters:format(jpeg)/pic1691099.jpg",
      "thumbnail": "https://cf.geekdo-images.com/c_GmyHR6gi9ZCkIQaSL0ZA__thumb/img/qb4-X5Os5xj5HSw2SxIZ1MZJ2lI=/fit-in/200x150/filters:strip_icc()/pic1691099.jpg",
      "minPlayers": 2,
      "maxPlayers": 8,
      "playingTime": 120,
      "isExpansion": false,
      "yearPublished": 1994,
      "bggRating": 0.0,
      "averageRating": 6.34206,
      "rank": 4165,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 9209,
      "name": "Ticket to Ride",
      "image": "https://cf.geekdo-images.com/ZWJg0dCdrWHxVnc0eFXK8w__original/img/LgzEsQlF3xkSEQLoorc8ntiYiIY=/0x0/filters:format(jpeg)/pic38668.jpg",
      "thumbnail": "https://cf.geekdo-images.com/ZWJg0dCdrWHxVnc0eFXK8w__thumb/img/a9rsFV6KR0aun8GobhRU16aU8Kc=/fit-in/200x150/filters:strip_icc()/pic38668.jpg",
      "minPlayers": 2,
      "maxPlayers": 5,
      "playingTime": 60,
      "isExpansion": false,
      "yearPublished": 2004,
      "bggRating": 0.0,
      "averageRating": 7.39373,
      "rank": 232,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 170416,
      "name": "Vast: The Crystal Caverns",
      "image": "https://cf.geekdo-images.com/CeXtELC0X1xjwuend_7pTg__original/img/y-f2dDCvwurzjcgFPbkj00CbXN8=/0x0/filters:format(jpeg)/pic2962290.jpg",
      "thumbnail": "https://cf.geekdo-images.com/CeXtELC0X1xjwuend_7pTg__thumb/img/FdE8SHtb503f9ZOk_TYyxS-sJQg=/fit-in/200x150/filters:strip_icc()/pic2962290.jpg",
      "minPlayers": 1,
      "maxPlayers": 5,
      "playingTime": 150,
      "isExpansion": false,
      "yearPublished": 2016,
      "bggRating": 0.0,
      "averageRating": 7.11397,
      "rank": 853,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 262543,
      "name": "Wavelength",
      "image": "https://cf.geekdo-images.com/z4fbPdmJg_5yphJEvql4ZA__original/img/bP1gM8RC-o5iz20_WazBaBNDHnU=/0x0/filters:format(png)/pic4552862.png",
      "thumbnail": "https://cf.geekdo-images.com/z4fbPdmJg_5yphJEvql4ZA__thumb/img/bxLuHVLF-Y06jWRSKA-tuQ3YYcE=/fit-in/200x150/filters:strip_icc()/pic4552862.png",
      "minPlayers": 2,
      "maxPlayers": 12,
      "playingTime": 45,
      "isExpansion": false,
      "yearPublished": 2019,
      "bggRating": 0.0,
      "averageRating": 7.28224,
      "rank": 451,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    },
    {
      "gameId": 190082,
      "name": "Whitehall Mystery",
      "image": "https://cf.geekdo-images.com/LA-CPp3BnCHkJa8ut85aIQ__original/img/0OqPWgqiD32midVjoYvwTvHZ62Y=/0x0/filters:format(jpeg)/pic3360633.jpg",
      "thumbnail": "https://cf.geekdo-images.com/LA-CPp3BnCHkJa8ut85aIQ__thumb/img/jva8lwK8a53YcK0fC7pSdr2iV3c=/fit-in/200x150/filters:strip_icc()/pic3360633.jpg",
      "minPlayers": 2,
      "maxPlayers": 4,
      "playingTime": 60,
      "isExpansion": false,
      "yearPublished": 2017,
      "bggRating": 0.0,
      "averageRating": 7.55245,
      "rank": 659,
      "numPlays": 0,
      "rating": -1.0,
      "owned": true,
      "preOrdered": false,
      "forTrade": false,
      "previousOwned": false,
      "want": false,
      "wantToPlay": false,
      "wantToBuy": false,
      "wishList": false,
      "userComment": ""
    }
  ]